# Generated by Django 2.2 on 2026-03-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='address',
        ),
    ]
